### ISSUE TITLE
Symlinks are ignored

### ISSUE THREAD

**Issue by ryandesign** [sandreas/m4b-tool#52] opened 2019-09-26 23:51 UTC
Using m4b-tool 0.4.2 installed using MacPorts on macOS High Sierra, I'm trying to create an m4b file from a folder of AIFF files. But these files don't have any silence at the beginning or end, so combining them as-is results in one chapter running immediately into the next, which isn't very pleasant. One wants a couple seconds of silence between chapters. To that end, I've used `sox` to create a 2-second-long silence file which I would like to place between each chapter. The way that occurred to me to do that was to create several symlinks to the silence file:

```
$ ls -l source/
total 288
lrwxr-xr-x  1 rschmidt  wheel     26 Sep 26 18:27 0s.aiff -> ../silence/silence0.5.aiff
-rw-r--r--  1 rschmidt  staff  84504 Sep 24 18:32 1.aiff
lrwxr-xr-x  1 rschmidt  wheel     26 Sep 26 18:27 1s.aiff -> ../silence/silence2.0.aiff
-rw-r--r--  1 rschmidt  staff  22760 Sep 24 18:32 2.aiff
lrwxr-xr-x  1 rschmidt  wheel     26 Sep 26 18:27 2s.aiff -> ../silence/silence2.0.aiff
-rw-r--r--  1 rschmidt  staff  21112 Sep 24 18:32 3.aiff
lrwxr-xr-x  1 rschmidt  wheel     26 Sep 26 18:27 3s.aiff -> ../silence/silence2.0.aiff
-rw-r--r--  1 rschmidt  staff  26152 Sep 24 18:32 4.aiff
lrwxr-xr-x  1 rschmidt  wheel     26 Sep 26 18:27 4s.aiff -> ../silence/silence2.0.aiff
-rw-r--r--  1 rschmidt  staff  32728 Sep 24 18:32 5.aiff
lrwxr-xr-x  1 rschmidt  wheel     26 Sep 26 18:27 5s.aiff -> ../silence/silence2.0.aiff
-rw-r--r--  1 rschmidt  staff  21408 Sep 24 18:32 6.aiff
lrwxr-xr-x  1 rschmidt  wheel     26 Sep 26 18:28 6s.aiff -> ../silence/silence2.0.aiff
-rw-r--r--  1 rschmidt  staff  33784 Sep 24 18:32 7.aiff
lrwxr-xr-x  1 rschmidt  wheel     26 Sep 26 18:28 7s.aiff -> ../silence/silence2.0.aiff
-rw-r--r--  1 rschmidt  staff  31804 Sep 24 18:32 8.aiff
-rw-r--r--  1 rschmidt  wheel     29 Sep 26 18:19 chapters.txt
```

But this doesn't work: m4b-tool ignores the symlinks.

If I copy the silence files instead of making symlinks, that works, but of course that takes up a little more disk space. I suppose I could use hardlinks. But the point is that it was unexpected that symlinks were silently ignored.

**Comment by sandreas** [comment] 2019-09-27 04:28
Thank you for reporting. Since this is two things, that could be improved, i would see this as issue (no symlink support) as well as feature request (add silence between chapters / files).

I think the second one is the more important one in your case, so i would concentrate on this feature first. My suggestion is to introduce new parameter `--add-silence=2000`, which would add a silence between chapters, that is 2000ms long. Would that solve your problem?

**Comment by sandreas** [comment] 2019-09-27 21:16
Added `--add-silence=<ms>` and `--trim-silence` (boolean flag) for merge command... 

- e.g. `--add-silence=2000` for 2 seconds of silence between chapter files
- e.g. `--trim-silence` for trying to remove silence at the beginning and end of tracks (this is experimental)
- e.g. `--add-silence=2000 --trim-silence` for normalizing all silences to 2 seconds

`--trim-silence` is very experimental, it might get removed before release. Here is a testing build, be careful, it might be unstable and cause data loss.

[m4b-tool.tar.gz](https://github.com/sandreas/m4b-tool/files/3664551/m4b-tool.tar.gz)

**Comment by ryandesign** [comment] 2019-10-06 13:53
This is a good idea, but I will probably still have to do some manual insertion of silences into my files. In this audiobook, I have the audio of the chapter titles in separate files from the content of the chapters. I will want to join those with a short silence, while I will want a longer silence between chapters. In another audiobook, I have a chapter that begins in the last track of one disc and finishes in the first track of the next disc. These probably have sufficient silence padding already and just need to be joined with no additional silence.

What about the symlink issue? Should I file a new ticket for that?

**Comment by sandreas** [comment] 2019-10-06 14:27
Hey there,

> This is a good idea, but I will probably still have to do some manual insertion of silences into my files. 

Ok, i think i have to admit that i clearly misunderstood the key message of this issue. You would like to manually specify a custom audio file in between the chapters by yourself using system tools, because it is a very special case. 
While you could also use **hardlinks** instead of symlinks to achieve your goal with the current version of `m4b-tool`, the result might not be what you expect, because `m4b-tool` would add a chapter for each silence file with an empty name (or if you specify a tag title for the silence file, with the specified name). Sample:

```
00:00:00.000 Intro
00:04:17.153 
00:04:19.153 My Chapter 1
00:09:22.078
00:09:24.078 My Chapter 2
00:14:32.500 
00:14:34.500 My Chapter 3
```

To overcome this problem, it might be possible to add a flag `--remove-blank-chapters`. Would that be needed?

> What about the symlink issue? Should I file a new ticket for that?
No, I'll reopen this one, although i think, symlinks should not be necessary to achieve your goal, it is a feature that could be helpful. But it will defintely take some time to implement and it might take long to ship the feature, since it is very specific.

**Comment by ryandesign** [comment] 2019-10-06 14:51
I realize that if I have m4b-tool derive chapter names from filenames using what I described above, then the result won't be what I want. In addition, a third audiobook I'm trying to convert came on several audio CDs, each of which has only a single track, and a fourth audiobook has 20 or so tracks per disc, but the tracks were cut with no regard for where chapters begin and end. With all this in mind, I'm planning to write additional scripts that split and rejoin the original audio into complete chapters, which I can then give to m4b-tool. I don't expect m4b-tool to help me with that preprocessing.

All that I wanted to point out in this issue was that, in the course of my experiments, I noticed that symlinks weren't supported, and I thought they should be, and I was trying to provide some context for why I was using symlinks.

**Comment by sandreas** [comment] 2019-10-06 16:07
> All that I wanted to point out in this issue was that, in the course of my experiments, I noticed that symlinks weren't supported, and I thought they should be, and I was trying to provide some context for why I was using symlinks.

Great, so the description of the issue is indeed valid and it will be fixed in the (not too) near future. Thank you for pointing this out and giving some context - it is really helpful for me and further development to hear about use cases of `m4b-tool` (I'm still surprised, that the little tool i wrote for myself with such a complex feature set is gaining so much attention).

Regarding the chapters: I'm planning something **BIG** for `v.0.5.0`, so keep in touch ;)

**Closed** 2019-10-21 08:01 UTC

**Comment by sandreas** [comment] 2019-10-21 08:05
Should be fixed in [latest release](https://github.com/sandreas/m4b-tool/releases/tag/latest) - Please read the description carefully
