### ISSUE TITLE
Genre separator is escaped

### ISSUE THREAD

**Issue by Net-Felix** [sandreas/m4b-tool#64] opened 2019-12-09 06:52 UTC
Hi,

when i convert a audiobook that has multiple genres, the separator gets escaped.

The command i use:
`/usr/local/bin/m4b-tool merge --no-cache --use-filenames-as-chapters --no-chapter-reindexing --jobs 32 --ffmpeg-threads 32 "input folder" -o "output.m4b"
`
input file id3tag:
genre           : Thriller;Psychothriller
this is the result:
genre           : Thriller\;Psychothriller

this breaks multi genre

**Comment by sandreas** [comment] 2019-12-09 23:20
Thanks for reporting. I'll take a look in the next days.
BTW: 32 cores? What a monster machine ;)

**Comment by Net-Felix** [comment] 2019-12-09 23:30
> BTW: 32 cores? What a monster machine ;)

Dual CPU Server ^^

**Comment by sandreas** [comment] 2019-12-09 23:39
Yeah I got the main problem. Github removed the \\ but i get the idea... :-)

**Comment by sandreas** [comment] 2019-12-10 01:35
This *seems* to be fixed in the latest [pre-release](https://github.com/sandreas/m4b-tool/releases/tag/latest). I reworked the whole tagging for the next release and therefore most of the tagging issues should be fixed. The latest *pre-release* is pretty stable (I already use it in production) but be careful - it might cause data loss. To install, just extract the `tar.gz`, place the `m4b-tool.phar` as `m4b-tool` in your `$PATH` and make it executable (`chmod +x m4b-tool`). The rest of the dependencies are still the same.

If it does not work, I need more information about what version you got, which tool you use to show the `genre` tag, etc. As a last option we maybe got to play some `build` ping pong (I build a new version, you test it), since i could not reproduce the issue on my system with the latest code.

**Comment by Net-Felix** [comment] 2019-12-10 06:48
Looks nice with latest version!

done a quick test with ffprobe and mp3tag

Thanks!

**Comment by sandreas** [comment] 2019-12-10 06:50
Great, thanks for the quick feedback :-)

**Closed by sandreas** 2019-12-10 06:50 UTC
