### ISSUE TITLE
Converting mp3 to mp3 (with/out --no-conversion) chapters misaligned

### ISSUE THREAD

**Issue by aaronsewall** [sandreas/m4b-tool#71] opened 2020-02-12 04:28 UTC
Related to this closed ticket, https://github.com/sandreas/m4b-tool/issues/38

When I convert a directory of mp3 files to m4b, the chapters are aligned perfectly. When I convert from a directory of mp3s to a single mp3, with or without --no-conversion, the chapters aren't correctly aligned. I also tried manually providing the chapters file from the successful m4b run.

Comparing the m4b run and a normal mp3 run of the m4b-tool.log files, the [milliseconds:protected] attribute actually differs. 

Comparing the m4b run to a normal mp3 run with the chapters.txt used from the m4b run, something odder happens.  The [milliseconds:protected] is correct but the array index becomes the same as the milliseconds:protected attribute. 

Attached is logs from my experiments. The original files are available here: https://librivox.org/history-of-a-six-weeks-tour-by-percy-bysshe-shelley/
[mp3 offset.zip](https://github.com/sandreas/m4b-tool/files/4189822/mp3.offset.zip)

**Comment by sandreas** [comment] 2020-02-12 05:28
Thanks for reporting and for your efforts to reproduce the problem.

I think this might have something to do with `ffmpeg` - unfortunately `ffmpeg` does not detect lengths correctly. For `mp4` it works, because `mp4tags` is used.

I will try some other possibilities, but i try to prevent another dependency to a binary utility, so perhaps this php library will solve the problem:
https://github.com/wapmorgan/MediaFile

I'll take a look in the next days.

**Comment by sandreas** [comment] 2020-02-13 18:11
Ok, i now prefer `MediaFile` lib to detect length for non-mp4 audio files. Depending on how accurate it is, the bug now might be fixed. I have to verify that the problem is fixed, which might take a few days.

**Comment by sandreas** [comment] 2020-02-13 22:05
Ok, seems to be a `ffmpeg` *behaviour* (i don't want to call it issue, because i don't know, whats the reason for this - it might be the de/muxing step when creating a new file). You can try it yourself:

1. copy your result mp3 file to `merged.mp3`
2. create a file `ffmeta.txt` with the following contents:
```
;FFMETADATA1
title=01 - Preface.

album=History of a Six Weeks' Tour

genre=Speech

artist=Percy Bysshe Shelley

track=1

encoder=Lavf58.29.100

[CHAPTER]
TIMEBASE=1/1000
START=0
END=196437
title=01 - Preface.
[CHAPTER]
TIMEBASE=1/1000
START=196437
END=381591
title=02 - Author's Introduction.
[CHAPTER]
TIMEBASE=1/1000
START=381591
END=1712027
title=03 - France.
[CHAPTER]
TIMEBASE=1/1000
START=1712027
END=2653177
title=04 - Switzerland.
[CHAPTER]
TIMEBASE=1/1000
START=2653177
END=3279154
title=05 - Germany.
[CHAPTER]
TIMEBASE=1/1000
START=3279154
END=3640978
title=06 - Holland.
[CHAPTER]
TIMEBASE=1/1000
START=3640978
END=4214143
title=07 - Letters Written During a
[CHAPTER]
TIMEBASE=1/1000
START=4214143
END=4657969
title=08 - Letters Written During a
[CHAPTER]
TIMEBASE=1/1000
START=4657969
END=6200600
title=09 - Letters Written During a
[CHAPTER]
TIMEBASE=1/1000
START=6200600
END=7782426
title=10 - Letters Written During a
[CHAPTER]
TIMEBASE=1/1000
START=7782426
END=8352603
title=11 - Mont Blanc. Lines Written
```

3. import the `ffmeta.txt` chapters by (this will take some time, `ffmpeg` has to transcode the file to change metadata):
```
'ffmpeg' '-hide_banner' '-i' 'merged.mp3' '-i' 'ffmeta.txt' '-map_metadata' '1' 'merged.new.mp3'
```

4. export a new `ffmeta-after-import.txt` from the file you just imported:
```
'ffmpeg' '-hide_banner' '-i' 'merged.new.mp3' '-f' 'ffmetadata' 'ffmeta-after-import.txt'
```

5. diff `ffmeta.txt` and `ffmeta-after-import.txt`

Because the chapters did not change between import and export, i would expect, that the chapters are at the same time, but the times are different. `ffmpeg` seems to change something here while importing chapters, whatever the reason is... I think, i cannot do much about it - perhaps switching `ffmpeg` to another tool, that is able to import metadata without re-encoding the whole file would be the only option.

What do you think?

**Comment by aaronsewall** [comment] 2020-03-03 04:12
Thanks for digging into this and sorry it took so long to get back to you.

Not sure what to tell you about ffmpeg, it's disappointing it doesn't work here the way you would expect.

Following up on your suggestion I tried mp3chaps (python library) and made a fork (there were some issues around an updated dependency using bytestrings instead of strings). https://github.com/aaronsewall/mp3chaps

I'm now using the following workflow:

1. Import my mp3 files into m4b-tool and do a "fake" conversion to get out the generated chapters.txt file. e.g. `m4b-tool --no-conversion -vvv --jobs=12 --ffmpeg-threads=12 --output-file=output.m4b merge .` I'd love a way to generate this without needing to resort to this sort of hack, any ideas?
2. Use mp3wrap http://mp3wrap.sourceforge.net/ to combine my mp3 files non-destructively (this is nice because you can use mp3splt to unwrap them).
3. Use mp3chaps to add the id3 tag information to this joined file.

I can then modify id3 tag info if I want, but then I can listen to this in Listen Audiobook Player on Android and store it in my calibre library as a single mp3 file.

**Comment by sandreas** [comment] 2020-03-03 05:45
Thank you for your efforts and research. Podlove Publisher might have something in PHP i could use:
https://github.com/podlove/podlove-publisher/blob/192a2710b6ad3d0f5eff67f4daacb5d6dac6ab4a/lib/chapters_manager.php

I'll check the possibilities to import accurate chapters into MP3 files in the next time, but unfortunately it might take some time to fix.

**Comment by sandreas** [comment] 2020-03-19 09:21
Ok, i investigated further.

> I'd love a way to generate this without needing to resort to this sort of hack, any ideas?

The chapter generation unfortunately is build deeply into the `merge`-command. I already thought of extracting this into the `chapters` command (like `m4b-tool chapters --build-from-conversion my/input/dir`) , but this is a bit tricky. Estimating the chapter lengths without converting is pretty easy, so for your case it would be doable. The problem is, that this should also work, if a conversion is requested. So it might be possible to add a `--chapters-only` flag to the merge command, but this would take a bit of time. 

> I'm now using the following workflow:

I'm glad that you found a way to achieve your goals. It should not be too hard to read and write `ID3V2` with php, but unfortunately, I did not find a library, that is able to store chapters. So it would be interesting to learn, but i think at the moment i do not have enough time to implement this myself. But I'll leave this issue open for now, perhaps it will be fixed in the future.

Here some links with more information for writing ID3V2 tags in PHP:
https://github.com/wapmorgan/Mp3Info/blob/master/src/Mp3Info.php
https://web.archive.org/web/20200101072747/http://id3.org/id3v2-chapters-1.0
https://github.com/brokencube/id3/blob/master/src/Writer.php
https://github.com/JamesHeinrich/getID3/blob/master/getid3/write.id3v2.php
https://formats.kaitai.io/id3v2_3/index.html

**Comment by sandreas** [comment] 2020-06-11 15:00
If filed an issue in the `ffmpeg` project - I'm sorry there is no short term solution for this in `m4b-tool`, so i will close this issue for now.

**Closed by sandreas** 2020-06-11 15:00 UTC
