### ISSUE TITLE
MP3 files are being added 2 times.

### ISSUE THREAD

**Issue by marcmontecalvo** [sandreas/m4b-tool#115] opened 2021-01-07 13:20 UTC
I followed the directions here:
https://github.com/sandreas/m4b-tool#ubuntu

I then ran this command with a test book:
sudo m4b-tool merge -vvv --jobs=4 "/mnt/unionfs/scratch/mp3merge/Flatland/" --output-file="/mnt/unonfs/scratch/mp3merge/merged.m4b"

These are the original MP3 files for that test book:
![image](https://user-images.githubusercontent.com/6583561/103896624-41a1d580-50c0-11eb-943a-0e2bf1273be7.png)

Here is the logging output from running it:
```
➜  mp3merge sudo m4b-tool merge -vvv --jobs=4 "/mnt/unionfs/scratch/mp3merge/Flatland/" --output-file="/mnt/unonfs/scratch/mp3merge/merged.m4b"
ffmpeg -hide_banner -codecs
determine highest available audio codec
Your ffmpeg version cannot produce top quality aac using encoder aac instead of libfdk_aac
== load input files ==
reading metadata and streaminfo for file /mnt/unionfs/scratch/mp3merge/Flatland/01 - Flatland.mp3
searching for cover in /mnt/unionfs/scratch/mp3merge/Flatland
using cover  /mnt/unionfs/scratch/mp3merge/Flatland/cover.jpg
searching for description.txt in /mnt/unionfs/scratch/mp3merge/Flatland
checking file /mnt/unionfs/scratch/mp3merge/Flatland/description.txt, realpath:
file description.txt not found or too big
skip cover extraction, file /mnt/unionfs/scratch/mp3merge/Flatland/cover.jpg already exists - use --force to overwrite
preparing conversion with 4 simultaneous jobs, please wait...
   0 remaining /    8 total, preparing next task \
using cover  /mnt/unionfs/scratch/mp3merge/Flatland/cover.jpg
searching for chapters.txt in /mnt/unionfs/scratch/mp3merge/Flatland
checking file /mnt/unionfs/scratch/mp3merge/Flatland/chapters.txt, realpath:
file chapters.txt not found or too big
rebuilding chapters from converted files title tags
ffmpeg -hide_banner -f concat -safe 0 -vn -i /mnt/unionfs/scratch/mp3merge/merged.m4b.listing.txt -max_muxing_queue_size 9999 -c copy -f mp4 /mnt/unionfs/scratch/mp3merge/merged-tmpfiles//tmp_merged.m4b
merging /mnt/unionfs/scratch/mp3merge/merged-tmpfiles//tmp_merged.m4b, this can take a while
++
tagging file /mnt/unionfs/scratch/mp3merge/merged-tmpfiles//tmp_merged.m4b with tag:
M4bTool\Audio\Tag Object
(
    [encoder] => m4b-tool
    [title] => 1 - Flatland
    [sortTitle] =>
    [artist] => Top 100 Sci-Fi Books
    [sortArtist] =>
    [genre] =>
    [writer] =>
    [album] => 86 - Flatland - Edwin A Abbott - 1884
    [sortAlbum] =>
    [disk] =>
    [disks] =>
    [albumArtist] =>
    [year] => 1884
    [track] =>
    [tracks] =>
    [cover] => SplFileInfo Object
        (
            [pathName:SplFileInfo:private] => /mnt/unionfs/scratch/mp3merge/Flatland/cover.jpg
            [fileName:SplFileInfo:private] => cover.jpg
        )

    [description] =>
    [longDescription] =>
    [comment] =>
    [copyright] =>
    [encodedBy] =>
    [performer] =>
    [language] =>
    [publisher] =>
    [lyrics] =>
    [chapters] => Array
        (
            [0] => M4bTool\Audio\Chapter Object
                (
                    [name:protected] => 1.1
                    [tag:protected] =>
                    [start:protected] => Sandreas\Time\TimeUnit Object
                        (
                            [milliseconds:protected] => 0
                        )

                    [length:protected] => Sandreas\Time\TimeUnit Object
                        (
                            [milliseconds:protected] => 742283
                        )

                )

            [1] => M4bTool\Audio\Chapter Object
                (
                    [name:protected] => 1.2
                    [tag:protected] =>
                    [start:protected] => Sandreas\Time\TimeUnit Object
                        (
                            [milliseconds:protected] => 742283
                        )

                    [length:protected] => Sandreas\Time\TimeUnit Object
                        (
                            [milliseconds:protected] => 742283
                        )

                )

            [2] => M4bTool\Audio\Chapter Object
                (
                    [name:protected] => 2.1
                    [tag:protected] =>
                    [start:protected] => Sandreas\Time\TimeUnit Object
                        (
                            [milliseconds:protected] => 1484566
                        )

                    [length:protected] => Sandreas\Time\TimeUnit Object
                        (
                            [milliseconds:protected] => 1531704
                        )

                )

            [3] => M4bTool\Audio\Chapter Object
                (
                    [name:protected] => 2.2
                    [tag:protected] =>
                    [start:protected] => Sandreas\Time\TimeUnit Object
                        (
                            [milliseconds:protected] => 3016270
                        )

                    [length:protected] => Sandreas\Time\TimeUnit Object
                        (
                            [milliseconds:protected] => 1531704
                        )

                )

            [4] => M4bTool\Audio\Chapter Object
                (
                    [name:protected] => 3.1
                    [tag:protected] =>
                    [start:protected] => Sandreas\Time\TimeUnit Object
                        (
                            [milliseconds:protected] => 4547974
                        )

                    [length:protected] => Sandreas\Time\TimeUnit Object
                        (
                            [milliseconds:protected] => 1685199
                        )

                )

            [5] => M4bTool\Audio\Chapter Object
                (
                    [name:protected] => 3.2
                    [tag:protected] =>
                    [start:protected] => Sandreas\Time\TimeUnit Object
                        (
                            [milliseconds:protected] => 6233173
                        )

                    [length:protected] => Sandreas\Time\TimeUnit Object
                        (
                            [milliseconds:protected] => 1685199
                        )

                )

            [6] => M4bTool\Audio\Chapter Object
                (
                    [name:protected] => 4.1
                    [tag:protected] =>
                    [start:protected] => Sandreas\Time\TimeUnit Object
                        (
                            [milliseconds:protected] => 7918372
                        )

                    [length:protected] => Sandreas\Time\TimeUnit Object
                        (
                            [milliseconds:protected] => 1126440
                        )

                )

            [7] => M4bTool\Audio\Chapter Object
                (
                    [name:protected] => 4.2
                    [tag:protected] =>
                    [start:protected] => Sandreas\Time\TimeUnit Object
                        (
                            [milliseconds:protected] => 9044812
                        )

                    [length:protected] => Sandreas\Time\TimeUnit Object
                        (
                            [milliseconds:protected] => 1126440
                        )

                )

        )

    [series] =>
    [seriesPart] =>
)

file /mnt/unionfs/scratch/mp3merge/merged-tmpfiles//tmp_merged.m4b is an MP4 file
mp4tags -help
check for sorting support in mp4tags
not supported - get a release from https://github.com/sandreas/mp4v2 for sorting support
mp4tags -song "1 - Flatland" -artist "Top 100 Sci-Fi Books" -year 1884 -album "86 - Flatland - Edwin A Abbott - 1884" -encodedby m4b-tool -type 2 /mnt/unionfs/scratch/mp3merge/merged-tmpfiles//tmp_merged.m4b
tagging file /mnt/unionfs/scratch/mp3merge/merged-tmpfiles//tmp_merged.m4b
mp4art --add /mnt/unionfs/scratch/mp3merge/Flatland/cover.jpg /mnt/unionfs/scratch/mp3merge/merged-tmpfiles//tmp_merged.m4b -f
adding cover /mnt/unionfs/scratch/mp3merge/Flatland/cover.jpg to /mnt/unionfs/scratch/mp3merge/merged-tmpfiles//tmp_merged.m4b
adding /mnt/unionfs/scratch/mp3merge/Flatland/cover.jpg -> /mnt/unionfs/scratch/mp3merge/merged-tmpfiles//tmp_merged.m4b

mp4chaps -i /mnt/unionfs/scratch/mp3merge/merged-tmpfiles//tmp_merged.m4b
importing chapters for /mnt/unionfs/scratch/mp3merge/merged-tmpfiles//tmp_merged.m4b
```

Here is the output file (its 2 times longer and much bigger than it should be):
![image](https://user-images.githubusercontent.com/6583561/103897136-0fdd3e80-50c1-11eb-8568-2db10d5af62b.png)

The merged chapters looks like this:
00:00:00.000 1.1
00:12:22.283 1.2
00:24:44.566 2.1
00:50:16.270 2.2
01:15:47.974 3.1
01:43:53.173 3.2
02:11:58.372 4.1
02:30:44.812 4.2

**Comment by sandreas** [comment] 2021-01-07 18:36
Which version are you using? If it is `0.4.2`, could you please check this with the latest pre-release?

**Comment by marcmontecalvo** [comment] 2021-01-07 19:21
I was using 0.4.2.  I just updated but I'm getting the same issue:
![image](https://user-images.githubusercontent.com/6583561/103934744-7da25e00-50f3-11eb-8473-ecff0922df58.png)


![image](https://user-images.githubusercontent.com/6583561/103934717-6f544200-50f3-11eb-99cf-9dbf68d0ead5.png)

```
➜  mp3mergesudo m4b-tool merge -vvv --jobs=4 "/mnt/unionfs/scratch/mp3merge/Flatland/" --output-file="/mnt/unionfs/scratch/mp3merge/merged.m4b"
'ffmpeg' '-hide_banner' '-version'
ffmpeg version 4.0.0 or higher is required - installed version 3.4.8 is likely to cause errors or unexpected behaviour...
== load input files ==
searching for cover in /mnt/unionfs/scratch/mp3merge/Flatland
cover not found or not specified
'ffmpeg' '-nostats' '-loglevel' 'panic' '-hide_banner' '-i' '/mnt/unionfs/scratch/mp3merge/Flatland/Flatland.mp3' '-an' '-vcodec' 'copy' '/mnt/unionfs/scratch/mp3merge/Flatland/cover.jpg'
extracted cover to /mnt/unionfs/scratch/mp3merge/Flatland/cover.jpg
preparing conversion with 4 simultaneous jobs, please wait...
'ffmpeg' '-nostats' '-loglevel' 'panic' '-hide_banner' '-i' '/mnt/unionfs/scratch/mp3merge/Flatland/Flatland.mp3' '-map_metadata' '0' '-max_muxing_queue_size' '9999' '-strict' 'experimental' '-movflags' '+faststart' '-vn' '-ab' '64k' '-ar' '22050' '-ac' '0' '-acodec' 'aac' '-f' 'mp4' '/mnt/unionfs/scratch/mp3merge/merged-tmpfiles/1-converting.m4b'
'ffmpeg' '-nostats' '-loglevel' 'panic' '-hide_banner' '-i' '/mnt/unionfs/scratch/mp3merge/Flatland/Flatland.mp3' '-map_metadata' '0' '-max_muxing_queue_size' '9999' '-strict' 'experimental' '-movflags' '+faststart' '-vn' '-ab' '64k' '-ar' '22050' '-ac' '0' '-acodec' 'aac' '-f' 'mp4' '/mnt/unionfs/scratch/mp3merge/merged-tmpfiles/2-converting.m4b'
   0 remaining /    2 total, preparing next task /
searching for cover in /mnt/unionfs/scratch/mp3merge/Flatland
using cover /mnt/unionfs/scratch/mp3merge/Flatland/cover.jpg
merging 2 files into /mnt/unionfs/scratch/mp3merge/merged-tmpfiles/tmp_merged.m4b, this can take a while
'ffmpeg' '-nostats' '-loglevel' 'panic' '-hide_banner' '-f' 'concat' '-safe' '0' '-vn' '-i' '/mnt/unionfs/scratch/mp3merge/merged-tmpfiles/tmp_merged.m4b.listing.txt' '-max_muxing_queue_size' '9999' '-c' 'copy' '-f' 'mp4' '/mnt/unionfs/scratch/mp3merge/merged-tmpfiles/tmp_merged.m4b'
improving tags...
==> trying improver Ffmetadata
ffmetadata.txt not found - tags not improved


==> trying improver ChaptersTxt
chapters.txt not found - tags not improved


==> trying improver ChaptersFromOverdrive
'ffmpeg' '-hide_banner' '-i' '/mnt/unionfs/scratch/mp3merge/Flatland/Flatland.mp3' '-f' 'ffmetadata' '-'
'ffmpeg' '-hide_banner' '-i' '/mnt/unionfs/scratch/mp3merge/Flatland/Flatland.mp3' '-f' 'ffmetadata' '-'


==> trying improver ChaptersFromFileTracks
'ffmpeg' '-hide_banner' '-i' '/mnt/unionfs/scratch/mp3merge/merged-tmpfiles/1-finished.m4b' '-f' 'ffmetadata' '-'
'mp4info' '/mnt/unionfs/scratch/mp3merge/merged-tmpfiles/1-finished.m4b'
'ffmpeg' '-hide_banner' '-i' '/mnt/unionfs/scratch/mp3merge/merged-tmpfiles/2-finished.m4b' '-f' 'ffmetadata' '-'
'mp4info' '/mnt/unionfs/scratch/mp3merge/merged-tmpfiles/2-finished.m4b'
chapter count changed from 0 to 2


==> trying improver OpenPackagingFormat
metadata.opf not found - tags not improved


==> trying improver AudibleTxt
no audible.txt found - tags not improved


==> trying improver AudibleJson
no audible.json found - tags not improved


==> trying improver M4bToolJson
m4b-tool.json not found - tags not improved


==> trying improver Description
description.txt not found - tags not improved


==> trying improver ContentMetadataJson
content_metadata_*.json not found - tags not improved


==> trying improver AudibleChaptersJson
content_metadata_*.json not found - tags not improved
'ffmpeg' '-nostats' '-loglevel' 'panic' '-hide_banner' '-i' '/mnt/unionfs/scratch/mp3merge/merged-tmpfiles/tmp_merged.m4b' '-vn' '-c:a' 'copy' '-f' 'crc' '-'
'ffmpeg' '-hide_banner' '-i' '/mnt/unionfs/scratch/mp3merge/merged-tmpfiles/tmp_merged.m4b' '-af' 'silencedetect=noise=-30dB:d=1.75' '-f' 'null' '-'
running silence detection for file /mnt/unionfs/scratch/mp3merge/merged-tmpfiles/tmp_merged.m4b with min length 00:00:01.750
silence detection finished


==> trying improver AdjustTooLongChapters
no chapter length adjustment required (max chapter length not provided or empty chapter list)


==> trying improver InputOptions
input options improved the following 2 properties:
        encoder: <empty> => m4b-tool
          cover: <empty> => /mnt/unionfs/scratch/mp3merge/Flatland/cover.jpg


'ffmpeg' '-hide_banner' '-i' '/mnt/unionfs/scratch/mp3merge/Flatland/Flatland.mp3' '-f' 'ffmetadata' '-'
tagFile - filename: /mnt/unionfs/scratch/mp3merge/merged-tmpfiles/tmp_merged.m4b
full tag: {"encoder":"m4b-tool","title":"1 - Flatland","artist":"Top 100 Sci-Fi Books","album":"86 - Flatland - Edwin A Abbott - 1884","year":{"date":"1884-01-01 00:00:00.000000","timezone_type":3,"timezone":"America\/New_York"},"track":"1\/12","cover":"\/mnt\/unionfs\/scratch\/mp3merge\/Flatland\/cover.jpg","encodedBy":"iTunes 10.2.2.14","type":2}
'mp4tags' '-help'
'mp4tags' '-A' '86 - Flatland - Edwin A Abbott - 1884' '-a' 'Top 100 Sci-Fi Books' '-t' '1/12' '-s' '1 - Flatland' '-y' '1884' '-e' 'iTunes 10.2.2.14' '-E' 'm4b-tool' '-i' '2' '/mnt/unionfs/scratch/mp3merge/merged-tmpfiles/tmp_merged.m4b'
'mp4chaps' '-i' '/mnt/unionfs/scratch/mp3merge/merged-tmpfiles/tmp_merged.m4b'
'mp4art' '--remove' '--art-any' '/mnt/unionfs/scratch/mp3merge/merged-tmpfiles/tmp_merged.m4b'
'mp4art' '--add' '/mnt/unionfs/scratch/mp3merge/Flatland/cover.jpg' '/mnt/unionfs/scratch/mp3merge/merged-tmpfiles/tmp_merged.m4b'
tagged file tmp_merged.m4b (artist: Top 100 Sci-Fi Books, name: 1 - Flatland, chapters: 2)
moved temporary tmp_merged.m4b to /mnt/unionfs/scratch/mp3merge/merged.m4b
successfully merged 2 files to /mnt/unionfs/scratch/mp3merge/merged.m4b
```

**Comment by sandreas** [comment] 2021-01-08 06:29
Thanks for the quick feedback. I'll check this in the next days if i can reproduce it (the logs should contain enough information).

**Comment by sandreas** [comment] 2021-01-08 12:31
Ok, I tried to reproduce this on different systems, but for me everything worked correctly. Using exact the same version of `m4b-tool` on Ubuntu, it is pretty likely that the problem is caused by your system (although I cannot guarantee, that it is no issue in `m4b-tool`).

To dig further, you could try to add the `--debug` flag, which results in keeping all the converted files and even more detailed output:

```
sudo m4b-tool merge --debug --jobs=4 "/mnt/unionfs/scratch/mp3merge/Flatland/" --output-file="/mnt/unionfs/scratch/mp3merge/merged.m4b"
```

Before doing so, here are some things that may be improved. Although it is pretty unlikely, that they solve the problem, I would recommend to regard them:

- Upgrade to a supported `ffmpeg` version, if possible (`ffmpeg version 4.0.0 or higher is required - installed version 3.4.8 is likely to cause errors or unexpected behaviour.`)
- Ensure, that there are no typos in your paths (`/mnt/unionfs/` vs.`/mnt/unonfs/`) - although the second command you provided was correct
- Don't use `sudo` - this should not cause any problems, but it is more common to do the conversion as a normal user
- On Linux, you should really consider to use the docker image with is much easier to use and provides many additional features

Further thoughts... you could try:
- to do the conversion locally, instead of mounting another filesystem
- to use a `--batch-pattern`
- to use a completely different output path, e.g. `/tmp` - just for a test

**Comment by sandreas** [comment] 2021-01-29 08:04
Closing this due to no further feedback. Feel free to reopen.

**Closed by sandreas** 2021-01-29 08:04 UTC

**Comment by misleadingrhino** [comment] 2021-10-16 02:19
Sorry to resurrect an old thread, but I just wanted to add that I had the same thing happen and it only happened on my mergerfs mount. Not sure why but when calling the same thing from a single disk, the collection of files works as expected so there are no doubles.
