### ISSUE TITLE
How to convert to MP3/M4A instead of M4B

### ISSUE THREAD

**Issue by nemosmithasf** [sandreas/m4b-tool#78] opened 2020-04-29 00:45 UTC
I saw on issue #71 that its possible to convert to MP3 (which is useful for book players that don't support M4B).

However, I can't figure out how to do this. Can somebody please advise?

This is what I've tried (and has not worked)
`m4b-tool merge -v --jobs=2 --no-conversion --output-file="output/" --batch-pattern="input/%n" --audio-format="m4a" "input/"`

**Comment by sandreas** [comment] 2020-04-29 06:01
If you need `mp3` as result:
- `--no-conversion` => keep source audio format, i think this might not be what you would like to do
- `--audio-format="m4a"` => destination format is `m4a` not `mp3` as intended

Try
```
m4b-tool merge -v --jobs=2 --output-file="output/" --batch-pattern="input/%n" --audio-format="mp3" "input/"
```

Perhaps add:

- `--audio-bitrate=128k`
- `--audio-channels=2`
- `--audio-samplerate=44100`

if you need it.

**Comment by nemosmithasf** [comment] 2020-04-29 09:53
I should've clarified, I tried `--audio-format="m4a"` and `--audo-format"mp3"`, both still resulted in a `m4b` file

**Comment by sandreas** [comment] 2020-04-30 04:49
Ah ok now i understand. Thanks for reporting, I'll take a look in the next days. Would you mind telling me which version you used?

**Comment by sandreas** [comment] 2020-05-02 21:14
Ok, should be fixed. Next pre-release is coming soon.

**Closed by sandreas** 2020-05-02 21:14 UTC
