### ISSUE TITLE
Chapters are off

### ISSUE THREAD

**Issue by moritztk** [sandreas/m4b-tool#38] opened 2019-08-07 14:55 UTC
Just merged an audiobook with many files (>130). Unfortunately the chapter markers are a bit off. 
At the beginning of the audiobook it's just a little bit, but the chapters towards the end are off by a few seconds.

**Comment by sandreas** [comment] 2019-08-07 17:19
Hey there,

thank you for reporting. To analyse this, i would need the following things:

- Which operating system are you using / did you use the docker image?
- What command did you use? (e.g. `m4b-tool merge data/book --output-file=test.m4b`)
- What kind of files did you merge? (e.g. `mp3`, `m4a`, `flac`...)

As soon as i get this information, i can try to reproduce the problem...

**Comment by moritztk** [comment] 2019-08-08 13:28
> Which operating system are you using / did you use the docker image?
Docker image on fedora 30

> What command did you use? (e.g. m4b-tool merge data/book --output-file=test.m4b)
```
m4b-tool merge -v --jobs=2 --output-file="output/" "input/" 
```

> What kind of files did you merge? (e.g. mp3, m4a, flac...)
mp3

**Comment by sandreas** [comment] 2019-08-08 17:17
Thank you. 

Sounds like a file specific issue - I maybe require the files to reproduce the problem, but before that i'll check your use case with some of my samples.

One thing i did not test, is providing a directory for the `--output-file="output/"`, usually you would specify a filename - e.g. `--output-file="output/merged.m4b"`, but that can't be the problem in my opinion.

I'll get back to you when I know more.

**Comment by sandreas** [comment] 2019-08-10 05:46
I can indeed confirm a little offset on my testing set... (in my case it is about 1,5 seconds on file 300). I also noticed, that it should not be possible to start a "simple" `merge` providing a directory as output.

This is something i have to investigate further, because i can't remember this happening in older m4b-tool versions... unfortunately this might take some time.

**Closed** 2019-08-10 11:42 UTC
Labels: bug

**Comment by sandreas** [comment] 2019-08-10 11:57
First of all: Thank you very much for reporting this, i did not notice the problem. Now it should be fixed for the next release. In the meantime, here is a bleeding edge version that should work:

[m4b-tool.tar.gz](https://github.com/sandreas/m4b-tool/files/3488793/m4b-tool.tar.gz)

To use it in the docker image, just replace `ARG M4B_TOOL_DOWNLOAD_LINK="https://github.com/sandreas/m4b-tool/releases/latest/download/m4b-tool.phar"` with the link to the bleeding edge version in the `Dockerfile`


Feedback is welcome, i hope it works for you, too...



To integrate a custom m4b-tool-
