### ISSUE TITLE
Problem with german Umlauts

### ISSUE THREAD

**Issue by kaileu** [sandreas/m4b-tool#7] opened 2018-03-19 18:18 UTC
Hi,

if the Input or the putput file contains whitespaces the merge process Fails.
Environment: Windows10

with the parameter php m4b-tool.phar merge --output-file="D:\Drachenigel (Die bla Seiner igel 3).m4b" INPUTFOLDER

```
PHP Notice:  Undefined offset: 1 in phar://D:/Programme/m4b-tool-php/m4b-tool.phar/src/library/M4bTool/Command/AbstractCommand.php on line 202

Notice: Undefined offset: 1 in phar://D:/Programme/m4b-tool-php/m4b-tool.phar/src/library/M4bTool/Command/AbstractCommand.php on line 202

In MergeCommand.php line 324:

  could not get duration for file D:\Drachenigel (Die bla Seiner igel 3)-tmpfiles\1-1-finsihed.m4b
```

**Comment by sandreas** [comment] 2018-03-20 23:15
I tried to merge an audiobook with whitespaces on windows, linux and macos... it worked for me. I think the issue is not because of using whitespaces in directory or filenames.

The error seems to occur, when mp4info.exe or other requirements are not installed correctly in %PATH%. Could you try to call 

```
mp4info
```
 from the command line and ensure, that the mp4info.exe is available in your %Path%?

Expected output would be:
```
C:\Users\sandreas\Temp>mp4info
usage: mp4info <file-name>
```

**Comment by kaileu** [comment] 2018-03-21 13:51
Thanks for digging into this Problem.
I am sorry i realised that the Problem wasn't the whitespace its the german umlauts like ä ö ü.

**Comment by sandreas** [comment] 2018-03-21 19:24
Thanks for clearing things up. This indeed is a bug. Reason:

- Only happens on Windows Systems, because PHP uses Win32 API for file access
- Win32 API internally uses Windows-1252 charset for filenames (instead of utf-8)
- mp4v2 expects all params to be utf-8 encoded

Should be fixed within the next release.

**Closed** 2018-03-21 19:28 UTC
Labels: bug

**Comment by sandreas** [comment] 2018-03-30 09:07
I released a v.0.3 beta - could you check if the issue with the umlauts is solved?

**Comment by kaileu** [comment] 2018-04-06 09:31
It works great.
Thanks

**Comment by sandreas** [comment] 2018-04-06 12:01
Cool - thank you for your feedback.
