### ISSUE TITLE
Error when merging files that have no cover

### ISSUE THREAD

**Issue by gennaios** [sandreas/m4b-tool#36] opened 2019-05-21 22:38 UTC
Hello,

I forgot exactly why I remove the covers before merging files. Perhaps it was some error using --no-conversion that I'm unsure if it remains valid and the step remains required. When first removing covers using AtomicParsley :

`for i in *.m4b ; do ; AtomicParsley "$i"  --artwork REMOVE_ALL --overWrite ; done`

and then merging :

`merge .  --no-conversion --fix-mime-type --output-file="/Users/.../Desktop/temp/1.m4b"`

I get the following error :

`extracting cover to /Users/.../Desktop/temp2/....jpg failed`

Perhaps m4b-tool assumes there is a cover and then shows as such. Maybe instead a warning or if there's no cover, just be silent ?

**Comment by sandreas** [comment] 2019-05-21 23:56
Does this result in stopping the merge? In my opinion it just should be a hint, that there is not cover available in the file.

If you do not want to use covers, you could use `--skip-cover`...

**Comment by gennaios** [comment] 2019-05-22 01:16
The merge completes. I haven't test listened to them yet but peeked at the chapters text file and all looks fine. A hint indeed is preferable though perhaps it might be more elegant to be silent w/o any warning or info.

**Comment by sandreas** [comment] 2019-05-23 08:58
The problem is, that i cannot tell for every file type, if an error occured or if the file just does not contain a cover (i did not find an `ffmpeg` option to check for existing coverart without extracting it...).
The best compromise in my opinion was to show a **warning** (not an error), if `--skip-cover` is not provided. I also think that it is good practice, to show a warning, if something is wrong or missing, that should be there - even when it is not a real error that results in a damaged file... 
I'm afraid, there is no better solution than the current behaviour at the moment...

If your merge is working and there is no other problem, i would close this bug due to external limitations... ok?

**Comment by gennaios** [comment] 2019-05-23 23:19
Merge is working fine. I think I was previously using `--skip-cover` though from not having used m4b-tool in a while, I picked a command from my command history. You can indeed close the issue. Thank you.

**Comment by sandreas** [comment] 2019-05-24 06:20
You're welcome :-)

**Closed by sandreas** 2019-05-24 06:20 UTC
