### ISSUE TITLE
Issue with adding chapters to m4b audiobook using Musicbrainz

### ISSUE THREAD

**Issue by rardias** [sandreas/m4b-tool#125] opened 2021-02-06 18:28 UTC
First of all, I would like to thank you, @sandreas, for this awesome tool.

**I've encountered an issue when adding chapters to a m4b audiobook using Musicbrainz id:**
`m4b-tool chapters -m e483845b-453c-41eb-80c9-c22180a06249 "./Dune Saga/Dune Chronicles I_ Dune.m4b" -v`

**The resulting error stack trace:**
```
PHP Fatal error:  Uncaught Error: Call to undefined function M4bTool\Parser\simplexml_load_string() in phar:///usr/local/bin/m4b-tool/src/library/Parser/MusicBrainzChapterParser.php:77
Stack trace:
#0 phar:///usr/local/bin/m4b-tool/src/library/Command/ChaptersCommand.php(154): M4bTool\Parser\MusicBrainzChapterParser->parseRecordings('<?xml version="...')
#1 phar:///usr/local/bin/m4b-tool/vendor/symfony/console/Command/Command.php(255): M4bTool\Command\ChaptersCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 phar:///usr/local/bin/m4b-tool/vendor/symfony/console/Application.php(1000): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 phar:///usr/local/bin/m4b-tool/vendor/symfony/console/Application.php(271): Symfony\Component\Console\Application->doRunCommand(Object(M4bTool\Command\ChaptersCommand), Object(Symfony\Component\Console\Input\ArgvInput in phar:///usr/local/bin/m4b-tool/src/library/Parser/MusicBrainzChapterParser.php on line 77
an error occured, that has not been caught:
Array
(
    [type] => 1
    [message] => Uncaught Error: Call to undefined function M4bTool\Parser\simplexml_load_string() in phar:///usr/local/bin/m4b-tool/src/library/Parser/MusicBrainzChapterParser.php:77
Stack trace:
#0 phar:///usr/local/bin/m4b-tool/src/library/Command/ChaptersCommand.php(154): M4bTool\Parser\MusicBrainzChapterParser->parseRecordings('<?xml version="...')
#1 phar:///usr/local/bin/m4b-tool/vendor/symfony/console/Command/Command.php(255): M4bTool\Command\ChaptersCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 phar:///usr/local/bin/m4b-tool/vendor/symfony/console/Application.php(1000): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 phar:///usr/local/bin/m4b-tool/vendor/symfony/console/Application.php(271): Symfony\Component\Console\Application->doRunCommand(Object(M4bTool\Command\ChaptersCommand), Object(Symfony\Component\Console\Input\ArgvInput
    [file] => phar:///usr/local/bin/m4b-tool/src/library/Parser/MusicBrainzChapterParser.php
    [line] => 77
)
```

**Version(s) used:**
`m4b-tool 0.4.2` and `m4b-tool latest-59-g1c33feb`, using Docker in macOS Catalina.

Searching other issues, I've come across #40, but since it is closed, I don't know if it is related.

Thanks in advance, let me know if you require any other information.
Best  #regards,

**Comment by sandreas** [comment] 2021-02-07 07:07
Possible duplicate of #118 - I'll have to check that.

**Comment by sandreas** [comment] 2021-02-07 14:01
should be fixed in the latest release

**Comment by rardias** [comment] 2021-02-08 11:37
Using the latest pre-release from 2021.02.07 ([m4b-tool.tar.gz](https://github.com/sandreas/m4b-tool/files/5939116/m4b-tool.tar.gz)), the issue has been fixed.

Thank you very much, you can close the issue.
Best regards.

**Closed** 2021-02-08 11:44 UTC
