### ISSUE TITLE
merge mp3 with multiple dots fails

### ISSUE THREAD

**Issue by uffcd** [sandreas/m4b-tool#88] opened 2020-06-22 12:32 UTC
```preparing conversion with 6 simultaneous jobs, please wait...
0 remaining /    8 total, preparing next task \
using cover abook/xx/cover.jpg
merging 8 files into abook/xx/author - title-tmpfiles/tmp_author - title.m4b, this can take a while
could not merge to abook/xx/author - title-tmpfiles/tmp_author - title.m4b```

This happens when one or more of the mp3 have look like this `1 - Some Author - A Title with Dots ....mp3`

**Comment by sandreas** [comment] 2020-06-22 16:38
Thanks for reporting, I'll take a look in the next days.

**Comment by sandreas** [comment] 2020-06-24 17:08
Works for me with the latest pre-release on MacOS... Which `m4b-tool`-version and OS did you use?

**Comment by uffcd** [comment] 2020-06-24 17:17
→ m4b-tool --version
m4b-tool latest-25-gb4404ef

on ubuntu linux. would it help to zip an example?

**Comment by sandreas** [comment] 2020-06-24 17:50
Sure, but before sending files around at first the full command you executed would already help a lot (`m4b-tool merge ...`).
And are you using docker or just plain install?

**Comment by sandreas** [comment] 2020-06-25 11:12
Ok, thank you for sharing the required information in a private discussion. I'll try to reproduce it in the next days.

**Comment by sandreas** [comment] 2020-07-28 21:06
Maybe the latest pre-release fixed this. I would appreciate if you try again.

**Comment by uffcd** [comment] 2020-07-30 06:28
Thanks for the new version: testing with `m4b-tool latest-38-g3cb62ea`. output hasn't changed for me:

```searching for cover in abook/Rhys Bowen - Im Auftrag ihrer Majestaet 02 - Adel verpflichtet zum Mord
using cover abook/Rhys Bowen - Im Auftrag ihrer Majestaet 02 - Adel verpflichtet zum Mord/cover.jpg
skip cover extraction, file abook/Rhys Bowen - Im Auftrag ihrer Majestaet 02 - Adel verpflichtet zum Mord/cover.jpg already exists - use --force to overwrite
preparing conversion with 6 simultaneous jobs, please wait...
   0 remaining /  208 total, preparing next task -
using cover abook/Rhys Bowen - Im Auftrag ihrer Majestaet 02 - Adel verpflichtet zum Mord/cover.jpg
merging 208 files into abook/Rhys Bowen - Im Auftrag ihrer Majestaet 02 - Adel verpflichtet zum Mord/Rhys Bowen - Adel verpflichtet... zum Mord-tmpfiles/tmp_Rhys Bowen - Adel verpflichtet... zum Mord.m4b, this can take a while
could not merge to abook/Rhys Bowen - Im Auftrag ihrer Majestaet 02 - Adel verpflichtet zum Mord/Rhys Bowen - Adel verpflichtet... zum Mord-tmpfiles/tmp_Rhys Bowen - Adel verpflichtet... zum Mord.m4bsearching for cover in abook/Rhys Bowen - Im Auftrag ihrer Majestaet 02 - Adel verpflichtet zum Mord
using cover abook/Rhys Bowen - Im Auftrag ihrer Majestaet 02 - Adel verpflichtet zum Mord/cover.jpg
skip cover extraction, file abook/Rhys Bowen - Im Auftrag ihrer Majestaet 02 - Adel verpflichtet zum Mord/cover.jpg already exists - use --force to overwrite
preparing conversion with 6 simultaneous jobs, please wait...
   0 remaining /  208 total, preparing next task -
using cover abook/Rhys Bowen - Im Auftrag ihrer Majestaet 02 - Adel verpflichtet zum Mord/cover.jpg
merging 208 files into abook/Rhys Bowen - Im Auftrag ihrer Majestaet 02 - Adel verpflichtet zum Mord/Rhys Bowen - Adel verpflichtet... zum Mord-tmpfiles/tmp_Rhys Bowen - Adel verpflichtet... zum Mord.m4b, this can take a while
could not merge to abook/Rhys Bowen - Im Auftrag ihrer Majestaet 02 - Adel verpflichtet zum Mord/Rhys Bowen - Adel verpflichtet... zum Mord-tmpfiles/tmp_Rhys Bowen - Adel verpflichtet... zum Mord.m4bsearching for cover in abook/Rhys Bowen - Im Auftrag ihrer Majestaet 02 - Adel verpflichtet zum Mord
using cover abook/Rhys Bowen - Im Auftrag ihrer Majestaet 02 - Adel verpflichtet zum Mord/cover.jpg
skip cover extraction, file abook/Rhys Bowen - Im Auftrag ihrer Majestaet 02 - Adel verpflichtet zum Mord/cover.jpg already exists - use --force to overwrite
preparing conversion with 6 simultaneous jobs, please wait...
   0 remaining /  208 total, preparing next task -
using cover abook/Rhys Bowen - Im Auftrag ihrer Majestaet 02 - Adel verpflichtet zum Mord/cover.jpg
merging 208 files into abook/Rhys Bowen - Im Auftrag ihrer Majestaet 02 - Adel verpflichtet zum Mord/Rhys Bowen - Adel verpflichtet... zum Mord-tmpfiles/tmp_Rhys Bowen - Adel verpflichtet... zum Mord.m4b, this can take a while
could not merge to abook/Rhys Bowen - Im Auftrag ihrer Majestaet 02 - Adel verpflichtet zum Mord/Rhys Bowen - Adel verpflichtet... zum Mord-tmpfiles/tmp_Rhys Bowen - Adel verpflichtet... zum Mord.m4b```

**Comment by sandreas** [comment] 2021-06-01 17:17
Ok, since there was no further feedback and I could not reproduce it (neither on MacOS, Ubuntu 18.04 nor Windows), I'll close this for now. Feel free to reopen, if it still occours, but please provide the above information for further investigation, otherwise I can't do anything

**Closed** 2021-06-01 17:17 UTC
