### ISSUE TITLE
Merged file is incorrect length

### ISSUE THREAD

**Issue by Etothetaui** [sandreas/m4b-tool#135] opened 2021-06-01 16:45 UTC
I am trying to make n m4b file from several mp3 files and a chapter.txt file. Everything seems to be going fine but the resulting file is only 29ish hours and the mp3 files total to over 50 hours. The m4b files in the tmp folder total to the correct time so something wrong is happening after the conversion takes place.

The command I used is: `m4b-tool -vv merge "The Way of Kings/" --genre "Epic Fantasy" --writer "Brandon Sanderson" --year "2010" --series "The Stormlight Archive Arc 1" --output-file="The Way of Kings.m4b"`

Attached is the chapters.txt file I am using.
[chapters.txt](https://github.com/sandreas/m4b-tool/files/6577792/chapters.txt)

I am not sure why this isn't working because I have used this successfully many times now.

The other thing I notice is the resulting file seems to show up in vlc as "The Way of Kings - Part 01" even though the file name is "The Way of Kings.m4b" but there also doesn't seem to be a part 2 anywhere.

What exactly am I doing wrong here?

**Comment by sandreas** [comment] 2021-06-01 17:04
This might be a problem with my directory scanner... I came across this a few times in my own collection but i was not able to reproduce it. If your mp3 files are separated into multiple directories like this:
```
cd1/001.mp3
cd1/002.mp3
# ...
cd3/001.mp3
#...
cover.jpg
description.txt
# ...
```
it might help to put everything into one directory (if possible). But I'll check this in the next weeks, I'm still busy, but it is getting a bit better :-)

**Comment by Etothetaui** [comment] 2021-06-01 17:16
All the files are in one folder already. It's really weird. Does anything look off in the command I used or the chapters.txt file?

Of course if you are busy now don't worry about it. It's no rush :)

**Comment by sandreas** [comment] 2021-06-01 17:18
You can add the `--debug` flag and check the logfile, maybe it tells you something. **Be careful to remove personal information if you would like to provide it in this issue.**

**Comment by Etothetaui** [comment] 2021-06-01 17:31
I managed to copy the separate m4b files to a different directory before they were deleted automatically and their total time was correct. I ran this command from that folder and got the attached log file

`m4b-tool -vv --no-conversion merge . --genre "Epic Fantasy" --writer "Brandon Sanderson" --year "2010" --series "The Stormlight Archive Arc 1" --output-file="The Way of Kings.m4b" --debug`

[m4b-tool.log](https://github.com/sandreas/m4b-tool/files/6578337/m4b-tool.log)

**Comment by sandreas** [comment] 2021-06-02 10:46
Should be fixed with the latest pre-release (see also #122)

**Comment by Etothetaui** [comment] 2021-06-03 02:50
Seems to still be a problem. Attached is the new log file: 
[m4b-tool.log](https://github.com/sandreas/m4b-tool/files/6588563/m4b-tool.log)

**Comment by Etothetaui** [comment] 2021-06-03 02:57
It is weird, when I try it on the m4b files with this command it works fine:
`m4b-tool -vv --no-conversion merge . --genre "Epic Fantasy" --writer "Brandon Sanderson" --year "2010" --series "The Stormlight Archive Arc 1" --output-file="The Way of Kings.m4b" --debug`

It's now just not working when working with the mp3s

**Comment by sandreas** [comment] 2021-06-03 04:12
Ok, then I have to take a look again :-)

**Comment by sandreas** [comment] 2021-06-04 11:59
I improved the logging with the latest pre-release. Would you mind running the ORIGINAL command, that you would like to use (not where you tried to fix it by saving the temporary files)  with extra `--debug` flag and provide the resulting logfile?
*Beware* that this file might contain user specific or sensitive information, that you might wanna remove.
> Note: Using `--debug` preserves all temporary files automatically - no need for tricks

**Comment by Etothetaui** [comment] 2021-06-07 02:46
[m4b-tool.log](https://github.com/sandreas/m4b-tool/files/6605529/m4b-tool.log)

**Comment by sandreas** [comment] 2021-06-07 17:25
Mmh, everything looks good to me. The 46 files are being converted and merged correctly. 
There is a `chapters.txt` file showing a length of `45:29:09.088` (+ the length of the last track, which should be negligible)... is this accurate? If so, how long is the resulting file instead?

I had a problem like this once in my whole collection and I was not able to fix this. In my opinion the problem must have been `ffmpeg`, because using `fdkaac` everything worked. Since you are using the docker image, maybe you give it a try... use `--audio-profile=aac_he` to use `fdkaac` instead of `ffmpeg`. Resulting file should be very similar, maybe it takes a bit longer.

**Comment by sandreas** [comment] 2021-06-09 18:44
> Also for some reason the m4b shows up as "Part 01" in the playlist even though its only one file and the file name doesn't have "Part 01" in it.

This is the `album` Tag... since you are not providing all possible tags, `m4b-tool` tries to preserve the tags already present in the source `mp3` files. If you don't like that, you have multiple options:

- `--ignore-source-tags` - will leave all the tags empty, that are not specified
- `--album="manual value"` - you can set the album manually
- `--equate="title,album"` - set the value of `album` to the same value as `title`

The logfiles also show, that you may improve some of the tag fields:
```
INFO      1344345ms sortalbum        : The Stormlight Archive Arc 1 - 
INFO      1344345ms sortname         : The Stormlight Archive Arc 1 - 
INFO      1344343ms series               : The Stormlight Archive Arc 1
```

> The playlist of mp3 files is 45 hours something but the m4b file is only 29 hours.

So the resulting file is too short, this would mean that some content is missing - which is remarkable, because the logs say, that 46 files have been converted and the concat listing of `ffmpeg` also shows, that the 46 converted files have been merged correctly. So I suspect some kind of `ffmpeg` misbehaviour here, like I described above

With 
```
sudo pacman -S fdkaac
```
you maybe would be able to use the `--audio-profile=aac_he` option, I described above. You could also try to up/downgrade `ffmpeg`, but in my case with the bogus `mp3` files, that did not help.

**Comment by sandreas** [comment] 2023-10-31 02:48
Closed, because this issue is pretty old. If the problem still occurs and bothers you, feel free to reopen.

**Closed by sandreas** 2023-10-31 02:48 UTC
Labels: feedback requested
