### ISSUE TITLE
Chapters are not in sync

### ISSUE THREAD

**Issue by gitrep3** [sandreas/m4b-tool#195] opened 2022-09-12 19:50 UTC
Hello! Thanks for the great tool! 

I am trying to create an audiobook m4b but unfortunately the chapters become more and more desync over the whole merge process.

Command I used to to run m4b-tool `docker run -it --rm -v "$("$pwd".replace('\', '/')):/mnt" -w /mnt sandreas/m4b-tool:latest merge --audio-codec=libfdk_aac   "./" --jobs=32 -o "merge.m4b" --skip-cover --audio-bitrate="128k" --include-extensions="aac,alac,flac,mp3,wav" --debug`

I compared the result of m4b-tool with the result of merging all mp3s with mkvtoolnix into a mka file which produces perfect chapters. You can see the chapters of m4b-tool being 15s out of sync at the end of the audiobook

<details>
<summary>Check this side by side comparison:</summary>

| m4b-tool | mkvtoolnix |
| ------------- | ------------- |
| ## total-duration:: 18:47:45.000 | ## total-duration:: 18:47:45.000 |
| 00:00:00.000 1.1 | 00:00:00.000 1 |
| 00:03:33.179 2.1 | 00:03:33.132 2 |
| 00:07:10.641 3.1 | 00:07:10.550 3 |
| 00:11:28.124 4.1 | 00:11:27.987 4 |
| 00:14:07.308 5.1 | 00:14:07.125 5 |
| 00:16:49.130 6.1 | 00:16:48.901 6 |
| 00:20:24.059 7.1 | 00:20:23.784 7 |
| 00:22:52.428 8.1 | 00:22:52.108 8 |
| 00:25:30.332 9.1 | 00:25:29.966 9 |
| 00:28:19.678 10.1 | 00:28:19.265 10 |
| 00:32:56.857 11.1 | 00:32:56.398 11 |
| 00:37:28.028 12.1 | 00:37:27.522 12 |
| 00:39:09.978 13.1 | 00:39:09.426 13 |
| 00:43:52.277 14.1 | 00:43:51.679 14 |
| 00:47:09.443 15.1 | 00:47:08.799 15 |
| 00:50:54.691 16.1 | 00:50:54.001 16 |
| 00:54:50.310 17.1 | 00:54:49.573 17 |
| 00:57:11.260 18.1 | 00:57:10.477 18 |
| 00:59:59.299 19.1 | 00:59:58.471 19 |
| 01:02:34.277 20.1 | 01:02:33.403 20 |
| 01:05:16.152 21.1 | 01:05:15.232 21 |
| 01:08:39.640 22.1 | 01:08:38.673 22 |
| 01:10:36.323 23.1 | 01:10:35.310 23 |
| 01:13:21.672 24.1 | 01:13:20.613 24 |
| 01:16:09.502 25.1 | 01:16:08.397 25 |
| 01:19:33.120 26.1 | 01:19:31.970 26 |
| 01:24:37.884 27.1 | 01:24:36.688 27 |
| 01:29:16.003 28.1 | 01:29:14.761 28 |
| 01:31:22.325 29.1 | 01:31:21.037 29 |
| 01:33:36.431 30.1 | 01:33:35.098 30 |
| 01:37:23.429 31.1 | 01:37:22.050 31 |
| 01:40:28.161 32.1 | 01:40:26.735 32 |
| 01:43:39.371 33.1 | 01:43:37.899 33 |
| 01:47:15.841 34.1 | 01:47:14.324 34 |
| 01:48:58.052 35.1 | 01:48:56.489 35 |
| 01:51:51.159 36.1 | 01:51:49.550 36 |
| 01:56:35.365 37.1 | 01:56:33.710 37 |
| 02:01:37.491 38.1 | 02:01:35.790 38 |
| 02:04:30.154 39.1 | 02:04:28.407 39 |
| 02:07:46.928 40.1 | 02:07:45.135 40 |
| 02:12:07.571 41.1 | 02:12:05.733 41 |
| 02:15:23.065 42.1 | 02:15:21.181 42 |
| 02:19:43.865 43.1 | 02:19:41.935 43 |
| 02:21:45.380 44.1 | 02:21:43.405 44 |
| 02:24:23.075 45.1 | 02:24:21.054 45 |
| 02:27:34.285 46.1 | 02:27:32.218 46 |
| 02:30:20.940 47.1 | 02:30:18.827 47 |
| 02:33:16.241 48.1 | 02:33:14.082 48 |
| 02:36:17.446 49.1 | 02:36:15.241 49 |
| 02:39:48.849 50.1 | 02:39:46.598 50 |
| 02:41:27.821 51.1 | 02:41:25.524 51 |
| 02:45:15.864 52.1 | 02:45:13.521 52 |
| 02:48:24.827 53.1 | 02:48:22.438 53 |
| 02:50:37.183 54.1 | 02:50:34.748 54 |
| 02:55:33.588 55.1 | 02:55:31.108 55 |
| 02:58:01.879 56.1 | 02:57:59.352 56 |
| 03:00:43.675 57.1 | 03:00:41.103 57 |
| 03:02:34.794 58.1 | 03:02:32.175 58 |
| 03:07:18.112 59.1 | 03:07:15.447 59 |
| 03:10:31.438 60.1 | 03:10:28.727 60 |
| 03:15:07.703 61.1 | 03:15:04.946 61 |
| 03:19:31.403 62.1 | 03:19:28.600 62 |
| 03:21:59.824 63.1 | 03:21:56.975 63 |
| 03:26:30.525 64.1 | 03:26:27.630 64 |
| 03:30:31.002 65.1 | 03:30:28.061 65 |
| 03:33:44.615 66.1 | 03:33:41.628 66 |
| 03:38:18.999 67.1 | 03:38:15.966 67 |
| 03:41:46.170 68.1 | 03:41:43.091 68 |
| 03:44:53.096 69.1 | 03:44:49.971 69 |
| 03:48:41.374 70.1 | 03:48:38.203 70 |
| 03:51:41.874 71.1 | 03:51:38.657 71 |
| 03:55:50.135 72.1 | 03:55:46.872 72 |
| 04:00:45.051 73.1 | 04:00:41.743 73 |
| 04:05:04.728 74.1 | 04:05:01.374 74 |
| 04:09:01.678 75.1 | 04:08:58.278 75 |
| 04:13:37.655 76.1 | 04:13:34.210 76 |
| 04:17:00.829 77.1 | 04:16:57.338 77 |
| 04:19:17.835 78.1 | 04:19:14.298 78 |
| 04:22:16.767 79.1 | 04:22:13.184 79 |
| 04:24:30.429 80.1 | 04:24:26.801 80 |
| 04:27:50.886 81.1 | 04:27:47.212 81 |
| 04:29:34.063 82.1 | 04:29:30.343 82 |
| 04:33:15.157 83.1 | 04:33:11.392 83 |
| 04:36:26.080 84.1 | 04:36:22.268 84 |
| 04:40:40.768 85.1 | 04:40:36.910 85 |
| 04:42:54.247 86.1 | 04:42:50.343 86 |
| 04:45:44.794 87.1 | 04:45:40.845 87 |
| 04:48:41.663 88.1 | 04:48:37.668 88 |
| 04:52:49.637 89.1 | 04:52:45.596 89 |
| 04:56:46.587 90.1 | 04:56:42.500 90 |
| 05:00:09.108 91.1 | 05:00:04.975 91 |
| 05:04:02.871 92.1 | 05:03:58.693 92 |
| 05:06:49.291 93.1 | 05:06:45.067 93 |
| 05:10:09.409 94.1 | 05:10:05.139 94 |
| 05:14:26.761 95.1 | 05:14:22.445 95 |
| 05:18:18.931 96.1 | 05:18:14.569 96 |
| 05:21:21.860 97.1 | 05:21:17.452 97 |
| 05:26:16.881 98.1 | 05:26:12.427 98 |
| 05:30:22.687 99.1 | 05:30:18.187 99 |
| 05:33:01.009 100.1 | 05:32:56.463 100 |
| 05:36:35.729 101.1 | 05:36:31.137 101 |
| 05:39:36.307 102.1 | 05:39:31.669 102 |
| 05:43:24.977 103.1 | 05:43:20.293 103 |
| 05:47:40.318 104.1 | 05:47:35.588 104 |
| 05:51:10.571 105.1 | 05:51:05.795 105 |
| 05:54:45.422 106.1 | 05:54:40.600 106 |
| 05:57:16.691 107.1 | 05:57:11.823 107 |
| 05:59:35.290 1.2 | 05:59:30.376 108 |
| 06:03:23.725 2.2 | 06:03:18.765 109 |
| 06:05:44.257 3.2 | 06:05:39.251 110 |
| 06:10:23.709 4.2 | 06:10:18.657 111 |
| 06:14:24.656 5.2 | 06:14:19.558 112 |
| 06:17:44.095 6.2 | 06:17:38.951 113 |
| 06:20:35.426 7.2 | 06:20:30.236 114 |
| 06:25:07.955 8.2 | 06:25:02.719 115 |
| 06:28:04.301 9.2 | 06:27:59.019 116 |
| 06:31:33.353 10.2 | 06:31:28.025 117 |
| 06:35:16.223 11.2 | 06:35:10.850 118 |
| 06:39:52.749 12.2 | 06:39:47.330 119 |
| 06:44:32.279 13.2 | 06:44:26.814 120 |
| 06:48:11.858 14.2 | 06:48:06.347 121 |
| 06:52:03.323 15.2 | 06:51:57.766 122 |
| 06:55:16.989 16.2 | 06:55:11.385 123 |
| 06:58:09.025 17.2 | 06:58:03.375 124 |
| 07:00:27.050 18.2 | 07:00:21.354 125 |
| 07:03:00.382 19.2 | 07:02:54.641 126 |
| 07:06:06.472 20.2 | 07:06:00.685 127 |
| 07:09:54.776 21.2 | 07:09:48.943 128 |
| 07:11:40.905 22.2 | 07:11:35.026 129 |
| 07:14:46.499 23.2 | 07:14:40.574 130 |
| 07:19:35.067 24.2 | 07:19:29.096 131 |
| 07:21:18.270 25.2 | 07:21:12.254 132 |
| 07:24:06.832 26.2 | 07:24:00.770 133 |
| 07:27:45.627 27.2 | 07:27:39.519 134 |
| 07:32:40.961 28.2 | 07:32:34.807 135 |
| 07:34:32.759 29.2 | 07:34:26.559 136 |
| 07:38:33.680 30.2 | 07:38:27.434 137 |
| 07:42:36.090 31.2 | 07:42:29.798 138 |
| 07:45:12.792 32.2 | 07:45:06.455 139 |
| 07:46:55.212 33.2 | 07:46:48.828 140 |
| 07:51:26.905 34.2 | 07:51:20.476 141 |
| 07:55:12.179 35.2 | 07:55:05.703 142 |
| 07:59:25.978 36.2 | 07:59:19.457 143 |
| 08:03:56.548 37.2 | 08:03:49.981 144 |
| 08:06:50.805 38.2 | 08:06:44.192 145 |
| 08:09:14.342 39.2 | 08:09:07.682 146 |
| 08:12:04.288 40.2 | 08:11:57.583 147 |
| 08:16:13.803 41.2 | 08:16:07.052 148 |
| 08:19:23.054 42.2 | 08:19:16.257 149 |
| 08:22:05.686 43.2 | 08:21:58.843 150 |
| 08:25:12.743 44.2 | 08:25:05.854 151 |
| 08:27:25.439 45.2 | 08:27:18.503 152 |
| 08:30:23.300 46.2 | 08:30:16.319 153 |
| 08:34:06.771 47.2 | 08:33:59.744 154 |
| 08:38:07.352 48.2 | 08:38:00.280 155 |
| 08:41:06.049 49.2 | 08:40:58.931 156 |
| 08:43:50.327 50.2 | 08:43:43.163 157 |
| 08:48:48.038 51.2 | 08:48:40.828 158 |
| 08:53:23.780 52.2 | 08:53:16.525 159 |
| 08:57:05.788 53.2 | 08:56:58.487 160 |
| 09:00:24.730 54.2 | 09:00:17.383 161 |
| 09:02:31.966 55.2 | 09:02:24.574 162 |
| 09:05:54.853 56.2 | 09:05:47.415 163 |
| 09:09:52.169 57.2 | 09:09:44.685 164 |
| 09:13:24.669 58.2 | 09:13:17.139 165 |
| 09:16:05.394 59.2 | 09:15:57.818 166 |
| 09:19:36.849 60.2 | 09:19:29.227 167 |
| 09:23:29.881 61.2 | 09:23:22.213 168 |
| 09:26:14.524 62.2 | 09:26:06.810 169 |
| 09:28:53.159 63.2 | 09:28:45.400 170 |
| 09:32:19.128 64.2 | 09:32:11.323 171 |
| 09:37:49.283 65.2 | 09:37:41.432 172 |
| 09:39:56.258 66.2 | 09:39:48.361 173 |
| 09:42:55.138 67.2 | 09:42:47.196 174 |
| 09:47:25.813 68.2 | 09:47:17.824 175 |
| 09:52:11.351 69.2 | 09:52:03.317 176 |
| 09:56:17.523 70.2 | 09:56:09.442 177 |
| 10:01:16.645 71.2 | 10:01:08.518 178 |
| 10:03:33.468 72.2 | 10:03:25.295 179 |
| 10:06:51.444 73.2 | 10:06:43.225 180 |
| 10:10:37.554 74.2 | 10:10:29.289 181 |
| 10:13:13.107 75.2 | 10:13:04.796 182 |
| 10:16:12.222 76.2 | 10:16:03.865 183 |
| 10:19:15.752 77.2 | 10:19:07.349 184 |
| 10:21:33.542 78.2 | 10:21:25.093 185 |
| 10:23:48.563 79.2 | 10:23:40.068 186 |
| 10:26:10.532 80.2 | 10:26:01.991 187 |
| 10:30:23.208 81.2 | 10:30:14.621 188 |
| 10:34:49.807 82.2 | 10:34:41.175 189 |
| 10:37:15.407 83.2 | 10:37:06.729 190 |
| 10:40:05.406 84.2 | 10:39:56.681 191 |
| 10:42:39.365 85.2 | 10:42:30.595 192 |
| 10:47:12.051 86.2 | 10:47:03.235 193 |
| 10:50:12.969 87.2 | 10:50:04.107 194 |
| 10:52:45.021 88.2 | 10:52:36.113 195 |
| 10:54:20.701 89.2 | 10:54:11.748 196 |
| 10:56:58.291 90.2 | 10:56:49.292 197 |
| 11:00:46.804 91.2 | 11:00:37.759 198 |
| 11:04:22.830 92.2 | 11:04:13.739 199 |
| 11:08:19.049 93.2 | 11:08:09.912 200 |
| 11:09:50.863 94.2 | 11:09:41.681 201 |
| 11:12:18.919 95.2 | 11:12:09.690 202 |
| 11:15:18.766 96.2 | 11:15:09.491 203 |
| 11:18:31.047 97.2 | 11:18:21.726 204 |
| 11:22:01.248 98.2 | 11:21:51.881 205 |
| 11:24:06.264 99.2 | 11:23:56.851 206 |
| 11:27:27.453 100.2 | 11:27:17.994 207 |
| 11:30:45.533 101.2 | 11:30:36.028 208 |
| 11:35:11.741 102.2 | 11:35:02.190 209 |
| 11:40:13.553 103.2 | 11:40:03.957 210 |
| 11:43:38.765 104.2 | 11:43:29.122 211 |
| 11:47:48.568 105.2 | 11:47:38.879 212 |
| 11:51:14.929 106.2 | 11:51:05.194 213 |
| 11:54:01.375 107.2 | 11:53:51.594 214 |
| 11:58:40.539 108.1 | 11:58:30.712 215 |
| 12:02:19.021 109.1 | 12:02:09.148 216 |
| 12:04:24.455 110.1 | 12:04:14.536 217 |
| 12:09:01.869 1.3 | 12:08:51.904 218 |
| 12:12:22.640 2.3 | 12:12:12.629 219 |
| 12:16:22.098 3.3 | 12:16:12.041 220 |
| 12:19:32.838 4.3 | 12:19:22.735 221 |
| 12:22:08.939 5.3 | 12:21:58.791 222 |
| 12:26:40.397 6.3 | 12:26:30.203 223 |
| 12:30:11.669 7.3 | 12:30:01.429 224 |
| 12:32:37.165 8.3 | 12:32:26.879 225 |
| 12:35:50.439 9.3 | 12:35:40.107 226 |
| 12:37:34.975 10.3 | 12:37:24.597 227 |
| 12:40:21.499 11.3 | 12:40:11.075 228 |
| 12:43:10.113 12.3 | 12:42:59.643 229 |
| 12:46:41.072 13.3 | 12:46:30.556 230 |
| 12:49:18.166 14.3 | 12:49:07.604 231 |
| 12:52:52.573 15.3 | 12:52:41.965 232 |
| 12:55:38.470 16.3 | 12:55:27.816 233 |
| 12:58:31.525 17.3 | 12:58:20.825 234 |
| 13:01:45.060 18.3 | 13:01:34.314 235 |
| 13:04:02.275 19.3 | 13:03:51.483 236 |
| 13:06:54.938 20.3 | 13:06:44.100 237 |
| 13:10:19.470 21.3 | 13:10:08.587 238 |
| 13:13:44.133 22.3 | 13:13:33.204 239 |
| 13:18:12.927 23.3 | 13:18:01.952 240 |
| 13:21:03.056 24.3 | 13:20:52.035 241 |
| 13:24:07.187 25.3 | 13:23:56.120 242 |
| 13:26:06.560 26.3 | 13:25:55.447 243 |
| 13:29:25.424 27.3 | 13:29:14.265 244 |
| 13:31:30.962 28.3 | 13:31:19.757 245 |
| 13:35:34.574 29.3 | 13:35:23.323 246 |
| 13:39:40.328 30.3 | 13:39:29.031 247 |
| 13:42:16.247 31.3 | 13:42:04.903 248 |
| 13:46:09.488 32.3 | 13:45:58.099 249 |
| 13:50:47.189 33.3 | 13:50:35.754 250 |
| 13:53:00.616 34.3 | 13:52:49.135 251 |
| 13:55:04.822 35.3 | 13:54:53.295 252 |
| 13:56:55.888 36.3 | 13:56:44.316 253 |
| 14:00:00.228 37.3 | 13:59:48.610 254 |
| 14:04:11.676 38.3 | 14:04:00.012 255 |
| 14:08:21.244 39.3 | 14:08:09.534 256 |
| 14:13:08.428 40.3 | 14:12:56.672 257 |
| 14:17:22.227 41.3 | 14:17:10.425 258 |
| 14:20:58.488 42.3 | 14:20:46.641 259 |
| 14:23:39.971 43.3 | 14:23:28.077 260 |
| 14:27:47.893 44.3 | 14:27:35.953 261 |
| 14:32:35.782 45.3 | 14:32:23.797 262 |
| 14:36:42.137 46.3 | 14:36:30.105 263 |
| 14:38:58.281 47.3 | 14:38:46.203 264 |
| 14:43:02.337 48.3 | 14:42:50.213 265 |
| 14:46:38.076 49.3 | 14:46:25.906 266 |
| 14:51:10.631 50.3 | 14:50:58.415 267 |
| 14:54:09.981 51.3 | 14:53:57.720 268 |
| 14:56:37.671 52.3 | 14:56:25.364 269 |
| 14:59:58.677 53.3 | 14:59:46.324 270 |
| 15:02:51.732 54.3 | 15:02:39.333 271 |
| 15:06:46.749 55.3 | 15:06:34.304 272 |
| 15:10:40.225 56.3 | 15:10:27.735 273 |
| 15:13:54.204 57.3 | 15:13:41.668 274 |
| 15:17:46.844 58.3 | 15:17:34.262 275 |
| 15:20:17.068 59.3 | 15:20:04.440 276 |
| 15:23:22.322 60.3 | 15:23:09.648 277 |
| 15:27:16.164 61.3 | 15:27:03.444 278 |
| 15:32:00.265 62.3 | 15:31:47.499 279 |
| 15:33:56.190 63.3 | 15:33:43.379 280 |
| 15:39:02.548 64.3 | 15:38:49.690 281 |
| 15:43:08.093 65.3 | 15:42:55.189 282 |
| 15:45:36.750 66.3 | 15:45:23.800 283 |
| 15:47:42.915 67.3 | 15:47:29.919 284 |
| 15:50:49.736 68.3 | 15:50:36.695 285 |
| 15:54:50.135 69.3 | 15:54:37.047 286 |
| 15:58:36.062 70.3 | 15:58:22.928 287 |
| 16:02:03.729 71.3 | 16:01:50.549 288 |
| 16:05:26.302 72.3 | 16:05:13.077 289 |
| 16:08:50.234 73.3 | 16:08:36.962 290 |
| 16:11:20.380 74.3 | 16:11:07.062 291 |
| 16:14:46.114 75.3 | 16:14:32.750 292 |
| 16:18:00.015 76.3 | 16:17:46.605 293 |
| 16:21:31.548 77.3 | 16:21:18.092 294 |
| 16:23:38.863 78.3 | 16:23:25.361 295 |
| 16:28:15.702 79.3 | 16:28:02.154 296 |
| 16:30:44.646 80.3 | 16:30:31.052 297 |
| 16:33:41.280 81.3 | 16:33:27.640 298 |
| 16:35:14.688 82.3 | 16:35:01.001 299 |
| 16:37:05.232 83.3 | 16:36:51.499 300 |
| 16:40:31.985 84.3 | 16:40:18.206 301 |
| 16:43:09.053 85.3 | 16:42:55.228 302 |
| 16:45:06.781 86.3 | 16:44:52.910 303 |
| 16:48:16.763 87.3 | 16:48:02.846 304 |
| 16:50:30.242 88.3 | 16:50:16.280 305 |
| 16:53:24.760 89.3 | 16:53:10.752 306 |
| 16:55:52.267 90.3 | 16:55:38.213 307 |
| 16:57:22.932 91.3 | 16:57:08.832 308 |
| 17:00:00.131 92.3 | 16:59:45.984 309 |
| 17:02:12.853 93.3 | 17:01:58.660 310 |
| 17:04:13.402 94.3 | 17:03:59.163 311 |
| 17:06:10.947 95.3 | 17:05:56.662 312 |
| 17:07:59.140 96.3 | 17:07:44.809 313 |
| 17:09:48.038 97.3 | 17:09:33.661 314 |
| 17:13:41.880 98.3 | 17:13:27.457 315 |
| 17:17:11.506 99.3 | 17:16:57.037 316 |
| 17:19:17.932 100.3 | 17:19:03.418 317 |
| 17:21:13.935 101.3 | 17:20:59.375 318 |
| 17:24:39.983 102.3 | 17:24:25.377 319 |
| 17:27:45.551 103.3 | 17:27:30.899 320 |
| 17:31:22.518 104.3 | 17:31:07.819 321 |
| 17:33:19.645 105.3 | 17:33:04.900 322 |
| 17:35:59.795 106.3 | 17:35:45.005 323 |
| 17:39:20.461 107.3 | 17:39:05.625 324 |
| 17:41:32.582 108.2 | 17:41:17.700 325 |
| 17:43:31.145 109.2 | 17:43:16.218 326 |
| 17:45:55.126 110.2 | 17:45:40.152 327 |
| 17:50:00.749 111 | 17:49:45.730 328 |
| 17:53:57.778 112 | 17:53:42.712 329 |
| 17:56:35.734 113 | 17:56:20.623 330 |
| 17:58:26.748 114 | 17:58:11.591 331 |
| 18:00:37.563 115 | 18:00:22.360 332 |
| 18:04:36.394 116 | 18:04:21.145 333 |
| 18:08:54.791 117 | 18:08:39.496 334 |
| 18:13:27.634 118 | 18:13:12.293 335 |
| 18:17:30.331 119 | 18:17:14.944 336 |
| 18:21:07.846 120 | 18:20:52.414 337 |
| 18:24:37.734 121 | 18:24:22.255 338 |
| 18:27:41.551 122 | 18:27:26.027 339 |
| 18:31:08.356 123 | 18:30:52.786 340 |
| 18:34:36.075 124 | 18:34:20.459 341 |
| 18:39:20.777 125 | 18:39:05.116 342 |
| 18:41:44.131 126 | 18:41:28.423 343 |
| 18:45:33.793 127 | 18:45:18.040 344 |

</details>

**Comment by sandreas** [comment] 2022-09-12 20:20
> I am trying to create an audiobook m4b but unfortunately the chapters become more and more desync over the whole merge process.

Maybe `m4b-tool` tries to *adjust* chapter positions by performing a silence detection or post conversion to m4b. 
Are you sure the chapters are misplaced or did you only compare the textual results? 

If you are sure, this is very hard to reproduce without the files. Since I assume the files cannot be shared publicly, I could provide you an invitation to a private repository, where we can discuss how to share these files non-public so that I can investigate the problem.

What do you think?

**Comment by gitrep3** [comment] 2022-09-12 20:24
Thanks for your quick response!

Yes they are misplaced, thats why I analyzed it further and made the comparison with mkvtoolnix.

Feel free to send me the link, I'm going to upload the single files, the m4b with incorrect chapters and the mka with correct chapters for you to reproduce.

**Comment by sandreas** [comment] 2022-09-12 20:46
> Feel free to send me the link, I'm going to upload the single files, the m4b with incorrect chapters and the mka with correct chapters for you to reproduce.

I did send you an invite to a private repo. Please read the rules in the `README.md` before uploading anything and do not checkout / modifiy the private repository - it is only meant for communication.

**Comment by gitrep3** [comment] 2022-09-21 17:53
In case anyone else encounters this issue, currently I am using this workaround to automatically create a merged mka file with correct chapters:
`bash -c "mkvmerge --generate-chapters when-appending --engage append_and_split_flac $(find ~+ -type f -regex '.*\.\(mp3\|flac\)$' -printf '"%p" + ' | rev | cut -c4- | rev) --output \"$(pwd)/merge.mka\" --generate-chapters-name-template 'Kapitel <NUM:2>' --language 0:ger"`

In a full script it can look like this:
```sh
#!/bin/bash

for d in *; do
    if [ -d "$d" ] && [[ $d != _* ]]; then
        cd "$d"
        echo $(pwd)
        if [ ! -f "merge.mka" ]; then
          echo "Create merged MKA for $d"
          bash -c "mkvmerge --generate-chapters when-appending --engage append_and_split_flac $(find ~+ -type f -regex '.*\.\(mp3\|flac\)$' -printf '"%p" + ' | rev | cut -c4- | rev) --output \"$(pwd)/merge.mka\" --generate-chapters-name-template 'Kapitel <NUM:2>' --language 0:ger"
        fi
        if [ ! -f "merge.m4b" ]; then
          echo "Create 128kbit M4B for $d"
          powershell.exe -c "docker run -it --rm -v \"\$(\"\$pwd\".replace('\', '/')):/mnt\" -w /mnt sandreas/m4b-tool:latest merge --audio-codec=libfdk_aac './' --jobs=32 -o 'merge.m4b' --skip-cover  --audio-bitrate='128k' --include-extensions='mka'"
        fi
        cd ..
    fi
done
```
Most likely you have to adapt it to your needs, I have a somewhat messy setup with WSL + Hyper-V docker installation (due to #109)

**Comment by sandreas** [comment] 2022-09-23 03:28
I did some further investigation:

```bash
> mp4info 001-finished.m4b | grep secs
1       audio   MPEG-4 AAC LC, 213.179 secs, 67 kbps, 22050 Hz
>
> tone dump 001-finished.m4b | grep duration               
│          duration │ 00:03:33.134              │
> 
```
As you see, somehow `mp4info`, which I internally use for length determination, thinks that the file is `213179ms` (`213.179` secs, which seems to be incorrect), while `tone` (a tool that I developed to deal with audio metadata) thinks that the file is `213134ms` (`3m 33sec 134ms`, which is correct). This shows a *shift* of `45ms`.

Since `mp4info` has always been reliable and the most accurate tool to detect length, I have no idea, what is happening here, but it seems, that either `mp4info` has an issue, or the file is somehow bogus.

Can you confirm, that `mp4info` is not showing the correct length for the temporary `m4b` files?

Since this is not an issue with `m4b-tool`, but with an external application, the things I will do to fix this:

- [ ] submit an issue to `mp4v2` repository [over here](https://github.com/enzo1982/mp4v2)
- [ ] provide a way to use `tone` for length detection in `m4b-tool` (maybe as default way, if `tone` is installed)

**Comment by sandreas** [comment] 2022-09-23 10:40
Should be fixed in the latest pre-release and in official docker image `sandreas/m4b-tool:latest`

Since this is a bigger change it might cause other issues, feedback is welcome. Feel free to reopen, if not fixed.

**Closed by sandreas** 2022-09-23 10:40 UTC

**Comment by gitrep3** [comment] 2022-10-03 16:07
Much appreciated, works great! Now all my chapters are in sync with the audio stream 🥳

**Comment by sandreas** [comment] 2022-10-03 16:16
> Much appreciated, works great! Now all my chapters are in sync with the audio stream partying_face

Whoohoo, nice. Thanks for the feedback.
